#ifndef ASMX64_OPERAND_H
#define ASMX64_OPERAND_H 1

// Flags
enum class X64RegValue
{
REG_VALUE_0 = 0,
REG_VALUE_1 = 1,
REG_VALUE_2 = 2,
REG_VALUE_3 = 3,
REG_VALUE_4 = 4,
REG_VALUE_5 = 5,
REG_VALUE_6 = 6,
REG_VALUE_7 = 7,
REG_VALUE_8 = 8,
REG_VALUE_9 = 9,
REG_VALUE_10 = 10,
REG_VALUE_11 = 11,
REG_VALUE_12 = 12,
REG_VALUE_13 = 13,
REG_VALUE_14 = 14,
REG_VALUE_15 = 15,
REG_VALUE_16 = 16,
REG_VALUE_17 = 17,
REG_VALUE_18 = 18,
REG_VALUE_19 = 19,
REG_VALUE_20 = 20,
REG_VALUE_21 = 21,
REG_VALUE_22 = 22,
REG_VALUE_23 = 23,
REG_VALUE_24 = 24,
REG_VALUE_25 = 25,
REG_VALUE_26 = 26,
REG_VALUE_27 = 27,
REG_VALUE_28 = 28,
REG_VALUE_29 = 29,
REG_VALUE_30 = 30,
REG_VALUE_31 = 31,
//
Common = 0x100,                             // 通用寄存器标志
REG_8bit = 0x200,                           // 8位标志一般在opcode中
REG_16bit = 0x400,                          // 0x66扩展（opcode前加0x66前缀）
REG_32bit = 0x800,                          // 
REG_64bit = 0x1000,
//
EAX = Common | REG_32bit | REG_VALUE_0,
ECX = Common | REG_32bit | REG_VALUE_1,
EDX = Common | REG_32bit | REG_VALUE_2,
EBX = Common | REG_32bit | REG_VALUE_3,
ESP = Common | REG_32bit | REG_VALUE_4,
EBP = Common | REG_32bit | REG_VALUE_5,
ESI = Common | REG_32bit | REG_VALUE_6,
EDI = Common | REG_32bit | REG_VALUE_7,
//
AL = Common | REG_8bit | REG_VALUE_0,
CL = Common | REG_8bit | REG_VALUE_1,
DL = Common | REG_8bit | REG_VALUE_2,
BL = Common | REG_8bit | REG_VALUE_3,
AH = Common | REG_8bit | REG_VALUE_4,
CH = Common | REG_8bit | REG_VALUE_5,
DH = Common | REG_8bit | REG_VALUE_6,
BH = Common | REG_8bit | REG_VALUE_7,
//
AX = Common | REG_16bit | REG_VALUE_0,
CX = Common | REG_16bit | REG_VALUE_1,
DX = Common | REG_16bit | REG_VALUE_2,
BX = Common | REG_16bit | REG_VALUE_3,
SP = Common | REG_16bit | REG_VALUE_4,
BP = Common | REG_16bit | REG_VALUE_5,
SI = Common | REG_16bit | REG_VALUE_6,
DI = Common | REG_16bit | REG_VALUE_7,
//
REXPreflx_40 = 0x2000,                      // REX的0x40标志
REXPreflx_W = REXPreflx_40 | 0x4000,        // REX.W 标志 （扩展宽度为64位标志）
RAX = Common | REG_64bit | REXPreflx_W | REG_VALUE_0,
RCX = Common | REG_64bit | REXPreflx_W | REG_VALUE_1,
RDX = Common | REG_64bit | REXPreflx_W | REG_VALUE_2,
RBX = Common | REG_64bit | REXPreflx_W | REG_VALUE_3,
RSP = Common | REG_64bit | REXPreflx_W | REG_VALUE_4,
RBP = Common | REG_64bit | REXPreflx_W | REG_VALUE_5,
RSI = Common | REG_64bit | REXPreflx_W | REG_VALUE_6,
RDI = Common | REG_64bit | REXPreflx_W | REG_VALUE_7,
// SP、BP、SI、DI 的低8位寄存器使用时需要加 REX:0x40 扩展，不加就是 AH、CH、DH、BH
SPL = Common | REG_8bit | REXPreflx_40 | REG_VALUE_4,
BPL = Common | REG_8bit | REXPreflx_40 | REG_VALUE_5,
SIL = Common | REG_8bit | REXPreflx_40 | REG_VALUE_6,
DIL = Common | REG_8bit | REXPreflx_40 | REG_VALUE_7,
//
REXPreflx_E = REXPreflx_40 | 0x8000,        // 需要扩展REX.R / REX.X / REX.B (reg、r/m、SIB域) 、扩展到8~15号寄存器
//
R8B = Common | REG_8bit | REXPreflx_E | REG_VALUE_8,
R9B = Common | REG_8bit | REXPreflx_E | REG_VALUE_9,
R10B = Common | REG_8bit | REXPreflx_E | REG_VALUE_10,
R11B = Common | REG_8bit | REXPreflx_E | REG_VALUE_11,
R12B = Common | REG_8bit | REXPreflx_E | REG_VALUE_12,
R13B = Common | REG_8bit | REXPreflx_E | REG_VALUE_13,
R14B = Common | REG_8bit | REXPreflx_E | REG_VALUE_14,
R15B = Common | REG_8bit | REXPreflx_E | REG_VALUE_15,
//
R8W = Common | REG_16bit | REXPreflx_E | REG_VALUE_8,
R9W = Common | REG_16bit | REXPreflx_E | REG_VALUE_9,
R10W = Common | REG_16bit | REXPreflx_E | REG_VALUE_10,
R11W = Common | REG_16bit | REXPreflx_E | REG_VALUE_11,
R12W = Common | REG_16bit | REXPreflx_E | REG_VALUE_12,
R13W = Common | REG_16bit | REXPreflx_E | REG_VALUE_13,
R14W = Common | REG_16bit | REXPreflx_E | REG_VALUE_14,
R15W = Common | REG_16bit | REXPreflx_E | REG_VALUE_15,
//
R8D = Common | REG_32bit | REXPreflx_E | REG_VALUE_8,
R9D = Common | REG_32bit | REXPreflx_E | REG_VALUE_9,
R10D = Common | REG_32bit | REXPreflx_E | REG_VALUE_10,
R11D = Common | REG_32bit | REXPreflx_E | REG_VALUE_11,
R12D = Common | REG_32bit | REXPreflx_E | REG_VALUE_12,
R13D = Common | REG_32bit | REXPreflx_E | REG_VALUE_13,
R14D = Common | REG_32bit | REXPreflx_E | REG_VALUE_14,
R15D = Common | REG_32bit | REXPreflx_E | REG_VALUE_15,
//
R8 = Common | REG_64bit | REXPreflx_W | REXPreflx_E | REG_VALUE_8,
R9 = Common | REG_64bit | REXPreflx_W | REXPreflx_E | REG_VALUE_9,
R10 = Common | REG_64bit | REXPreflx_W | REXPreflx_E | REG_VALUE_10,
R11 = Common | REG_64bit | REXPreflx_W | REXPreflx_E | REG_VALUE_11,
R12 = Common | REG_64bit | REXPreflx_W | REXPreflx_E | REG_VALUE_12,
R13 = Common | REG_64bit | REXPreflx_W | REXPreflx_E | REG_VALUE_13,
R14 = Common | REG_64bit | REXPreflx_W | REXPreflx_E | REG_VALUE_14,
R15 = Common | REG_64bit | REXPreflx_W | REXPreflx_E | REG_VALUE_15,
//
SegmentReg = 0x10000,                       // 段寄存器标志
CtrlReg = 0x20000,                          // 控制寄存器(CR0~CR15)
DebugReg = 0x40000,                         // 调试寄存器(DR0~DR15)
X87Reg = 0x80000,                           // 浮点寄存器标志（ST0~ST7）
MMXReg = 0x100000,                          // MMX寄存器（MM0~MM7，实际是ST0~ST7的子集）
XMMReg = 0x200000,                          // XMM寄存器 SSE (128-bit) (XMM0~XMM31)
YMMReg = 0x400000,                          // YMM寄存器 AVX-2 (256-bit) (YMM0~YMM31)
ZMMReg = 0x800000,                          // ZMM寄存器 AVX-512 (512-bit) (ZMM0~ZMM31)
TMMReg = 0x1000000,                         // TMM寄存器 (一个寄存器1KB大小的寄存器) (TMM0~TMM8)
SSEVEX = 0x2000000,                         // SSE寄存器扩展（可以使用 XMM15~XMM31, YMM15~YMM31, ZMM15~ZMM31）
//
ES = SegmentReg | REG_VALUE_0,
CS = SegmentReg | REG_VALUE_1,
SS = SegmentReg | REG_VALUE_2,
DS = SegmentReg | REG_VALUE_3,
FS = SegmentReg | REG_VALUE_4,
GS = SegmentReg | REG_VALUE_5,
//
CR0 = CtrlReg | REG_VALUE_0,
CR1 = CtrlReg | REG_VALUE_1,
CR2 = CtrlReg | REG_VALUE_2,
CR3 = CtrlReg | REG_VALUE_3,
CR4 = CtrlReg | REG_VALUE_4,
CR5 = CtrlReg | REG_VALUE_5,
CR6 = CtrlReg | REG_VALUE_6,
CR7 = CtrlReg | REG_VALUE_7,
CR8 = CtrlReg | REXPreflx_E | REG_VALUE_8,
CR9 = CtrlReg | REXPreflx_E | REG_VALUE_9,
CR10 = CtrlReg | REXPreflx_E | REG_VALUE_10,
CR11 = CtrlReg | REXPreflx_E | REG_VALUE_11,
CR12 = CtrlReg | REXPreflx_E | REG_VALUE_12,
CR13 = CtrlReg | REXPreflx_E | REG_VALUE_13,
CR14 = CtrlReg | REXPreflx_E | REG_VALUE_14,
CR15 = CtrlReg | REXPreflx_E | REG_VALUE_15,
//
DR0 = DebugReg | REG_VALUE_0,
DR1 = DebugReg | REG_VALUE_1,
DR2 = DebugReg | REG_VALUE_2,
DR3 = DebugReg | REG_VALUE_3,
DR4 = DebugReg | REG_VALUE_4,
DR5 = DebugReg | REG_VALUE_5,
DR6 = DebugReg | REG_VALUE_6,
DR7 = DebugReg | REG_VALUE_7,
DR8 = DebugReg | REXPreflx_E | REG_VALUE_8,
DR9 = DebugReg | REXPreflx_E | REG_VALUE_9,
DR10 = DebugReg | REXPreflx_E | REG_VALUE_10,
DR11 = DebugReg | REXPreflx_E | REG_VALUE_11,
DR12 = DebugReg | REXPreflx_E | REG_VALUE_12,
DR13 = DebugReg | REXPreflx_E | REG_VALUE_13,
DR14 = DebugReg | REXPreflx_E | REG_VALUE_14,
DR15 = DebugReg | REXPreflx_E | REG_VALUE_15,
//
ST0 = X87Reg | REG_VALUE_0,
ST1 = X87Reg | REG_VALUE_1,
ST2 = X87Reg | REG_VALUE_2,
ST3 = X87Reg | REG_VALUE_3,
ST4 = X87Reg | REG_VALUE_4,
ST5 = X87Reg | REG_VALUE_5,
ST6 = X87Reg | REG_VALUE_6,
ST7 = X87Reg | REG_VALUE_7,
//
MM0 = MMXReg | REG_VALUE_0,
MM1 = MMXReg | REG_VALUE_1,
MM2 = MMXReg | REG_VALUE_2,
MM3 = MMXReg | REG_VALUE_3,
MM4 = MMXReg | REG_VALUE_4,
MM5 = MMXReg | REG_VALUE_5,
MM6 = MMXReg | REG_VALUE_6,
MM7 = MMXReg | REG_VALUE_7,
//
XMM0 = XMMReg | REG_VALUE_0,
XMM1 = XMMReg | REG_VALUE_1,
XMM2 = XMMReg | REG_VALUE_2,
XMM3 = XMMReg | REG_VALUE_3,
XMM4 = XMMReg | REG_VALUE_4,
XMM5 = XMMReg | REG_VALUE_5,
XMM6 = XMMReg | REG_VALUE_6,
XMM7 = XMMReg | REG_VALUE_7,
XMM8 = XMMReg | REXPreflx_E | REG_VALUE_8,
XMM9 = XMMReg | REXPreflx_E | REG_VALUE_9,
XMM10 = XMMReg | REXPreflx_E | REG_VALUE_10,
XMM11 = XMMReg | REXPreflx_E | REG_VALUE_11,
XMM12 = XMMReg | REXPreflx_E | REG_VALUE_12,
XMM13 = XMMReg | REXPreflx_E | REG_VALUE_13,
XMM14 = XMMReg | REXPreflx_E | REG_VALUE_14,
XMM15 = XMMReg | REXPreflx_E | REG_VALUE_15,
XMM16 = XMMReg | SSEVEX | REG_VALUE_16,
XMM17 = XMMReg | SSEVEX | REG_VALUE_17,
XMM18 = XMMReg | SSEVEX | REG_VALUE_18,
XMM19 = XMMReg | SSEVEX | REG_VALUE_19,
XMM20 = XMMReg | SSEVEX | REG_VALUE_20,
XMM21 = XMMReg | SSEVEX | REG_VALUE_21,
XMM22 = XMMReg | SSEVEX | REG_VALUE_22,
XMM23 = XMMReg | SSEVEX | REG_VALUE_23,
XMM24 = XMMReg | SSEVEX | REG_VALUE_24,
XMM25 = XMMReg | SSEVEX | REG_VALUE_25,
XMM26 = XMMReg | SSEVEX | REG_VALUE_26,
XMM27 = XMMReg | SSEVEX | REG_VALUE_27,
XMM28 = XMMReg | SSEVEX | REG_VALUE_28,
XMM29 = XMMReg | SSEVEX | REG_VALUE_29,
XMM30 = XMMReg | SSEVEX | REG_VALUE_30,
XMM31 = XMMReg | SSEVEX | REG_VALUE_31,
//
YMM0 = YMMReg | REG_VALUE_0,
YMM1 = YMMReg | REG_VALUE_1,
YMM2 = YMMReg | REG_VALUE_2,
YMM3 = YMMReg | REG_VALUE_3,
YMM4 = YMMReg | REG_VALUE_4,
YMM5 = YMMReg | REG_VALUE_5,
YMM6 = YMMReg | REG_VALUE_6,
YMM7 = YMMReg | REG_VALUE_7,
YMM8 = YMMReg | REG_VALUE_8,
YMM9 = YMMReg | REG_VALUE_9,
YMM10 = YMMReg | REG_VALUE_10,
YMM11 = YMMReg | REG_VALUE_11,
YMM12 = YMMReg | REG_VALUE_12,
YMM13 = YMMReg | REG_VALUE_13,
YMM14 = YMMReg | REG_VALUE_14,
YMM15 = YMMReg | REG_VALUE_15,
YMM16 = YMMReg | REG_VALUE_16,
YMM17 = YMMReg | REG_VALUE_17,
YMM18 = YMMReg | REG_VALUE_18,
YMM19 = YMMReg | REG_VALUE_19,
YMM20 = YMMReg | REG_VALUE_20,
YMM21 = YMMReg | REG_VALUE_21,
YMM22 = YMMReg | REG_VALUE_22,
YMM23 = YMMReg | REG_VALUE_23,
YMM24 = YMMReg | REG_VALUE_24,
YMM25 = YMMReg | REG_VALUE_25,
YMM26 = YMMReg | REG_VALUE_26,
YMM27 = YMMReg | REG_VALUE_27,
YMM28 = YMMReg | REG_VALUE_28,
YMM29 = YMMReg | REG_VALUE_29,
YMM30 = YMMReg | REG_VALUE_30,
YMM31 = YMMReg | REG_VALUE_31,
//
ZMM0 = ZMMReg | REG_VALUE_0,
ZMM1 = ZMMReg | REG_VALUE_1,
ZMM2 = ZMMReg | REG_VALUE_2,
ZMM3 = ZMMReg | REG_VALUE_3,
ZMM4 = ZMMReg | REG_VALUE_4,
ZMM5 = ZMMReg | REG_VALUE_5,
ZMM6 = ZMMReg | REG_VALUE_6,
ZMM7 = ZMMReg | REG_VALUE_7,
ZMM8 = ZMMReg | REG_VALUE_8,
ZMM9 = ZMMReg | REG_VALUE_9,
ZMM10 = ZMMReg | REG_VALUE_10,
ZMM11 = ZMMReg | REG_VALUE_11,
ZMM12 = ZMMReg | REG_VALUE_12,
ZMM13 = ZMMReg | REG_VALUE_13,
ZMM14 = ZMMReg | REG_VALUE_14,
ZMM15 = ZMMReg | REG_VALUE_15,
ZMM16 = ZMMReg | REG_VALUE_16,
ZMM17 = ZMMReg | REG_VALUE_17,
ZMM18 = ZMMReg | REG_VALUE_18,
ZMM19 = ZMMReg | REG_VALUE_19,
ZMM20 = ZMMReg | REG_VALUE_20,
ZMM21 = ZMMReg | REG_VALUE_21,
ZMM22 = ZMMReg | REG_VALUE_22,
ZMM23 = ZMMReg | REG_VALUE_23,
ZMM24 = ZMMReg | REG_VALUE_24,
ZMM25 = ZMMReg | REG_VALUE_25,
ZMM26 = ZMMReg | REG_VALUE_26,
ZMM27 = ZMMReg | REG_VALUE_27,
ZMM28 = ZMMReg | REG_VALUE_28,
ZMM29 = ZMMReg | REG_VALUE_29,
ZMM30 = ZMMReg | REG_VALUE_30,
ZMM31 = ZMMReg | REG_VALUE_31,
//
TMM0 = TMMReg | REG_VALUE_0,
TMM1 = TMMReg | REG_VALUE_1,
TMM2 = TMMReg | REG_VALUE_2,
TMM3 = TMMReg | REG_VALUE_3,
TMM4 = TMMReg | REG_VALUE_4,
TMM5 = TMMReg | REG_VALUE_5,
TMM6 = TMMReg | REG_VALUE_6,
TMM7 = TMMReg | REG_VALUE_7,
//
};


class X64Operand
{
	int a;
};

#endif // ASMX64_OPERAND_H


