<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="assembler\x86_64\X64Processor.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="assembler\x86_64\X64Processor.cs" />
  </ItemGroup>

</Project>
